version: "2"

services:
    9zilla:
        container_name: 9zilla
        hostname: 9zilla
        image: nobiki/9zilla:latest
        ports:
            -  "80:80"
            -  "443:443"
            -  "19022:22"
        networks:
            b0:
                ipv4_address: 172.18.0.100
        environment:
            - "TZ=Asia/Tokyo"
        volumes:
            - /var/containers/9zilla/etc/nginx/conf.d/:/etc/nginx/conf.d/
            - /var/containers/9zilla/etc/pki/tls/certs/:/etc/pki/tls/certs/
            - /var/containers/9zilla/var/lib/mysql/:/var/lib/mysql/
            - /var/containers/9zilla/usr/local/lib/behat/features/:/usr/local/lib/behat/features/
        # example: Docker for Mac
        # volumes:
        #     - /private/var/containers/9zilla/etc/nginx/conf.d/:/etc/nginx/conf.d/
        #     - /private/var/containers/9zilla/etc/pki/tls/certs/:/etc/pki/tls/certs/
        #     - /private/var/containers/9zilla/var/lib/mysql/:/var/lib/mysql/
        #     - /private/var/containers/9zilla/usr/local/lib/behat/features/:/usr/local/lib/behat/features/
        # example: Docker fro Windows
        # volumes:
        #     - C:\containers\9zilla\etc\nginx\conf.d\:/etc/nginx/conf.d/
        #     - C:\containers\9zilla\etc\pki\tls\certs\:/etc/pki/tls/certs/
        #     - C:\containers\9zilla\var\lib\mysql\:/var/lib/mysql/
        #     - C:\containers\9zilla\usr\local\lib\behat\features\:/usr/local/lib/behat/features/
        privileged: true
        command: /sbin/init

networks:
    b0:
        driver: bridge
        ipam:
            driver: default
            config:
                -  subnet: 172.18.0.0/16
                   gateway: 172.18.0.1

