FROM debian:jessie
MAINTAINER Naoaki Obiki

ARG username="9zilla"
ARG password="9zilla"

RUN apt-get update

#include "./include/vanilla.docker"
#include "./include/php.docker"
#include "./include/apache2.docker"
#include "./include/nvm.docker"
#include "./include/mariadb-client.docker"
