FROM debian:stretch
MAINTAINER Naoaki Obiki

RUN apt-get update && apt-get install -y sudo git systemd

#include "./include/useradd.docker"
#include "./include/base.docker"

#include "./include/apt-python.docker"
#include "./include/robotframework.docker"

#include "./include/xvfb.docker"
#include "./include/selenium.docker"
#include "./include/browser.docker"

COPY bootstrap.sh /
RUN chmod +x /bootstrap.sh

CMD ["/bootstrap.sh"]
